retain_objc_accessible: true
schemes:
- SwissTransfer
targets:
- SwissTransfer
- SwissTransferCore
- SwissTransferCoreUI
- SwissTransferResources
- SwissTransferTests
- SwissTransfer_SwissTransferResources
workspace: SwissTransfer.xcworkspace
