name: CI workflow

on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Test project
    runs-on: [ self-hosted, iOS ]

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup mise
        uses: jdx/mise-action@7e36c90d9ab29c415a2384db3006f3ec8a8cc654
        with:
          cache: false
      - name: Generate
        run: tuist install && tuist generate
      - name: Check implicit imports
        run: tuist inspect dependencies --only implicit
      - name: Build
        run: tuist build --clean "SwissTransfer"
