name: CI workflow

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Scan unused code
    runs-on: [ self-hosted, iOS ]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}
      - uses: jdx/mise-action@v2
        with:
          cache: false
          experimental: true
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate
        run: tuist install && tuist generate
      - name: Periphery
        run: periphery scan --retain-codable-properties --format github-actions --relative-results --strict
